# Домашнее задание №2: линейная регрессия и векторное дифференцирование (10 баллов).

**Дедлайн для всех групп: 29 сентября в 23:59**

* Максимальное количество баллов за задания в ноутбуке - 11, но больше 10 оценка не ставится, поэтому для получения максимальной оценки можно сделать не все задания.

* Некоторые задания будут по вариантам (всего 4 варианта). Чтобы выяснить свой вариант, посчитайте количество букв в своей фамилии, возьмете остаток от деления на 4 и прибавьте 1.

Выполнил: Тихонов Сергей

In [1]:
import numpy as np

## Многомерная линейная регрессия из sklearn

Применим многомерную регрессию из sklearn для стандартного датасета

In [2]:
from sklearn.datasets import make_regression

X, y = make_regression(n_samples = 10000)
print(X.shape, y.shape)

(10000, 100) (10000,)


У нас 10000 объектов и 100 признаков. Для начала решим задачу аналитически "из коробки".

In [3]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

np.random.seed(10)

reg = LinearRegression().fit(X, y)
print(mean_squared_error(y, reg.predict(X)))
reg.coef_

3.4090202783179854e-25


array([ 7.73439831e-14, -4.26325641e-14,  9.23705556e-14,  1.42108547e-14,
        3.55271368e-14, -4.97379915e-14, -5.68434189e-14,  4.11313962e+01,
       -4.61852778e-14, -3.19744231e-14, -1.59872116e-14, -6.21724894e-14,
       -1.11910481e-13, -7.10542736e-15,  5.41788836e-14,  3.37507799e-14,
       -1.06581410e-13, -1.49213975e-13, -1.59872116e-14, -1.06581410e-14,
       -3.90798505e-14, -9.76996262e-14, -4.97379915e-14,  4.26325641e-14,
       -7.10542736e-15,  1.42108547e-14,  9.44415381e+01,  2.90878432e-14,
       -2.30926389e-14, -3.90798505e-14, -3.19744231e-14,  2.25404796e+00,
        1.42108547e-14, -7.81597009e-14, -7.99360578e-14, -5.06261699e-14,
        5.88034064e+01,  6.75015599e-14,  9.44882996e+01,  3.14392419e+01,
        1.33226763e-14, -1.24344979e-14, -1.06581410e-13,  5.68434189e-14,
       -6.39488462e-14,  2.13162821e-14,  1.53654867e-13, -9.23705556e-14,
        1.42108547e-14,  6.75015599e-14, -5.06261699e-14,  9.99200722e-15,
       -3.37507799e-14,  

Теперь попробуем обучить линейную регрессию методом градиентного спуска "из коробки"

In [4]:
from sklearn.linear_model import SGDRegressor

np.random.seed(10)

reg = SGDRegressor(alpha=0.00000001).fit(X, y)
print(mean_squared_error(y, reg.predict(X)))
reg.coef_

4.2407172406143024e-12


array([-8.76182015e-08, -3.62160680e-08, -6.97482662e-08,  1.36085298e-08,
        2.50436321e-09, -3.17873933e-09,  4.02099556e-09,  4.11313957e+01,
        7.89504003e-09,  4.22724955e-08,  5.60872456e-08,  2.09859630e-08,
        3.69399382e-09,  1.50009840e-08,  9.46655792e-08,  6.51601005e-08,
        1.50555840e-09,  1.21854253e-08, -5.44350952e-09, -2.87193120e-08,
        3.37920104e-08, -1.60571705e-08, -3.71936713e-09, -1.06896931e-08,
       -2.99740712e-08, -2.82385713e-08,  9.44415372e+01,  2.47704950e-08,
        4.53549631e-08,  4.05832720e-08, -3.00886212e-08,  2.25404797e+00,
        1.43077307e-08, -6.57112901e-08,  5.38013920e-08,  8.78557596e-08,
        5.88034058e+01,  4.07560921e-09,  9.44882987e+01,  3.14392416e+01,
       -6.42111926e-09,  3.20300792e-08,  3.73041914e-08,  3.27720965e-08,
        1.86115876e-09, -3.19035243e-08,  5.34942349e-09,  4.98348129e-10,
        2.28947379e-08,  3.32766922e-08,  2.93533883e-08,  6.21251399e-08,
        4.71718484e-08, -

***Задание 1 (0.5 балла).*** Объясните, чем вызвано различие двух полученных значений метрики?


***Задание 2 (0.5 балла).*** Подберите гиперпараметры в методе градиентного спуска так, чтобы значение MSE было близко к значению MSE, полученному при обучении LinearRegression.

**Задание 1**
В первом случае веса считаются аналитическим путём:
$$
w = (X'X)^{-1}X'y
$$ 
Во втором с помощью итеративного метода (стохастического градиентного спуска), когда градиент считается не по всем объектам, а по некоторому батчу. Таким образом, минимуму функции могут отличаться. Поэтому важен осмысленный подбор гиперпараметра $\alpha$, чтобы за максимальное количество иттераций метод успел сойтись.


**Задание 2** Теперь попробуем подобрать параметр $\alpha$, чтобы MSE совпадали:


In [5]:
from sklearn.linear_model import SGDRegressor

np.random.seed(10)

reg = SGDRegressor(alpha=0.0000000095).fit(X, y)
print(mean_squared_error(y, reg.predict(X)))
reg.coef_

3.8272469092983366e-12


array([-8.32372704e-08, -3.44052669e-08, -6.62608565e-08,  1.29281072e-08,
        2.37914375e-09, -3.01980652e-09,  3.81994836e-09,  4.11313958e+01,
        7.50029458e-09,  4.01588826e-08,  5.32828798e-08,  1.99366697e-08,
        3.50929366e-09,  1.42509412e-08,  8.99323090e-08,  6.19020836e-08,
        1.43028522e-09,  1.15761630e-08, -5.17132582e-09, -2.72833522e-08,
        3.21024056e-08, -1.52543042e-08, -3.53339820e-09, -1.01552004e-08,
       -2.84753686e-08, -2.68266366e-08,  9.44415372e+01,  2.35319722e-08,
        4.30872130e-08,  3.85541097e-08, -2.85841733e-08,  2.25404797e+00,
        1.35923280e-08, -6.24257398e-08,  5.11113181e-08,  8.34629521e-08,
        5.88034058e+01,  3.87183267e-09,  9.44882988e+01,  3.14392416e+01,
       -6.10004572e-09,  3.04285819e-08,  3.54389885e-08,  3.11334951e-08,
        1.76810119e-09, -3.03083390e-08,  5.08194638e-09,  4.73421969e-10,
        2.17500046e-08,  3.16128480e-08,  2.78857227e-08,  5.90188796e-08,
        4.48132562e-08, -

## Ваша многомерная линейная регрессия

***Задание 3 (5 баллов)***. Напишите собственную многомерную линейную регрессию, оптимизирующую MSE методом *градиентного спуска*. Для этого используйте шаблонный класс. 

Критерий останова: либо норма разности весов на текущей и предыдущей итерациях меньше определенного значения (первый и третий варианты), либо модуль разности функционалов качества (MSE) на текущей и предыдущей итерациях меньше определенного значения (второй и четвертый варианты). Также предлагается завершать обучение в любом случае, если было произведено слишком много итераций.

***Задание 4 (2 балла)***. Добавьте l1 (первый и четвертый варианты) или l2 (второй и третий варианты) регуляризацию. 

In [221]:
class LinearRegression(object):
    def __init__(self, alpha, l_ratio, tol=0.001, max_iter=1000):
        '''
        Для начала необходимо инициализировать параметры
        alpha - это learning rate или шаг обучения
        l_ratio - параметр регуляризации
        tol - значение для критерия останова
        max_iter - максимальное количество итераций обучения
        '''
        
        self.l_ratio = l_ratio
        self.alpha = alpha
        self.tol = tol
        self.max_iter = max_iter

        self.w = None
        self.loss_history = None
             
    def fit(self, X, y):
        '''
        Метод для обучения линейной регрессии
        X - матрица признаков
        y - вектор правильных ответов
        '''
        X = np.hstack([X, np.ones([X.shape[0], 1])])
        self.w = np.random.uniform(-2, 2, (X.shape[1]))
        self.weight_history = [self.w]

        for i in range(self.max_iter):

            w_no_bias = self.w.copy()
            w_no_bias[-1] = 0
            self.w = self.w - self.l_ratio * (2 * (X.T @ (X @ self.w - y)) / len(X) + self.alpha * np.sign(w_no_bias))
            self.weight_history.append(self.w)

            if np.abs(mean_squared_error(y, X @ self.weight_history[-1]) - mean_squared_error(y, X @ self.weight_history[-2])) < self.tol:
                break

        return self.weight_history
   
    def predict(self, X):
        '''
        Метод для предсказаний линейной регрессии
        X - матрица признаков
        '''
        X = np.hstack([X, np.ones([X.shape[0], 1])])
        
        return X @ self.w

**Важные комментарии по имплементации класса:**

1. X = np.hstack([X, np.ones([X.shape[0], 1])]) - добавили столбец из единиц для константного признака (bias)
2. w_no_bias - из лекций известно, что bias не регуляризируется, поэтому убираем w_no_bias[-1] = 0 последний элемент из вектора весов.
3. Считаю, что в инициализации параметров класса ошибка. Alpha - это параметр регуляризации (как и везде в sklearn), а l_ratio - собственно learning rate.
4. Регуляризацию реализовал следующим образом: если $\alpha = 0$, то это обычная регрессия (оценки совпадают с OLS, так как функционал и градиент совпадают). Если $\alpha \neq 0$, то имеет место регрессия с регуляризацией, в моём варианте Lasso. Очень удобно и без лишних if :)

In [222]:
np.random.seed(10)
my_reg = LinearRegression(alpha=0, l_ratio=0.5) 
my_reg.fit(X, y)
assert mean_squared_error(y, my_reg.predict(X)) < 1e-3
print('You are amazing! Great work!')

You are amazing! Great work!


In [223]:
np.random.seed(10)
mean_squared_error(y, my_reg.predict(X))

3.4487916152541083e-06

In [224]:
np.random.seed(10)
y

array([ 215.19841037, -378.21747116, -137.70075467, ...,  250.4543156 ,
        212.81785398, -350.63415562])

In [225]:
np.random.seed(10)
my_reg.predict(X)

array([ 215.19758348, -378.21682991, -137.70197055, ...,  250.45348715,
        212.81078084, -350.63018008])

***Задание 5 (1 балл)***. Обучите линейную регрессию из коробки

* с l1-регуляризацией (from sklearn.linear_model import Lasso, **первый и четвертый вариант**) или с l2-регуляризацией (from sklearn.linear_model import Ridge, **второй и третий вариант**)
* со значением параметра регуляризации **0.1 - для первого и третьего варианта, 0.01 - для второго и четвертого варианта**. 

Обучите вашу линейную регрессию с тем же значением параметра регуляризации и сравните результаты. Сделайте выводы.

In [229]:
from sklearn.linear_model import Lasso

np.random.seed(10)

reg = Lasso(alpha=0.01, tol=0.001).fit(X, y)
print(mean_squared_error(y, reg.predict(X)))

0.0009984891234456107


In [234]:
np.random.seed(10)

my_reg_ridge = LinearRegression(alpha=0.01, l_ratio=0.25)
my_reg_ridge.fit(X, y)
mean_squared_error(y, my_reg_ridge.predict(X))

0.0009668368979658105

**Выводы:**

Результаты собственной имплементации Lasso и готовой версии из sklearn при заданном параметре регуляризации $\lambda = 0.01$ практически не отличаются. Результат вполне ожидаем, поскольку обе версии Lasso являются иттеративными (на основе градиентного спуска), то есть одинаково сходятся на одних и тех же данных. 

Разница могла быть в случае сравнения Ridge, поскольку там имеется аналитическое решение, которое может не совпадать с иттеративным при плохом подборе параметров. 

***Задание 6* (1 балл).***
Пусть $P, Q \in \mathbb{R}^{n\times n}$. Найдите $\nabla_Q tr(PQ)$

Сначала посчитаем $d(tr(PQ)$

Зная, что $tr(...)$ - линейное отображение по определению (сумма элементов, лежащих на главной диагонали) и что $d(...)$ - тоже линейное отображение по определению (линейная часть дифференцируемой функциий), можно заключить, что они коммутатируют:

$$d(tr(PQ)) = tr(d(PQ)) = tr(PdQ) = tr(PdQ)$$

$tr(PdQ)$ - сумма попарных произведений элементов главной диагонали матрицы, образованной произведением $P dQ$, а значит:

$$tr(PdQ) = <P^T, dQ>$$

Воспользуемся фактом, что $<\nabla_x f(x),dx>$:

$$\nabla_Qtr(PQ) = P^T$$

***Задание 7* (1 балл).***
Пусть $x, y \in \mathbb{R}^{n}, M \in \mathbb{R}^{n\times n}$. Найдите $\nabla_M x^T M y$

Note: 

1) $x^TMx$ - скаляр, так как вектор размера $1 \times n$ умножается на матрицу размера $n \times n$ умножается на вектор размера $n \times 1$.

2) $tr(\text{скаляр}) = \text{скаляр}$

3) $tr(ABC) = tr(BCA) = tr(CAB)$ (для матриц подходящего размера)

Сначала посчитаем $d(x^T M y)$

$$d(x^T M y) = \text{Воспользуемся Note 1 и 2} = d(tr(x^T M y)) = \text{Воспользуемся Note 3} = d(tr(yx^TM)) $$

Воспользуемся результатом задания 6:

$$tr(yx^TM) = <xy^T, M>$$

Воспользуемся фактом, что $<\nabla_x f(x),dx>$:

$$\nabla_M x^T M y = xy^T$$



Решения заданий 6 и 7 можно написать на листочке и отправить в anytask вместе с заполненным ноутбуком.